---
 - name: download motion software package
   get_url:
      url: https://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_stretch_motion_4.0.1-1_armhf.deb
      dest: /home/pi/pi_stretch_motion_4.0.1-1_armhf.deb

 - name: install downloaded motion package
   apt:
      deb: /home/pi/pi_stretch_motion_4.0.1-1_armhf.deb

# we are disabling the motion service to make it easier to run under pi user
# to facilitate calling scripts with Google credentials installed for user
 - name: disable motion service and run from script
   service:
      name: motion
      state: stopped
      enabled: no

 - name: copy file to start motion on boot
   copy:
      src: motion
      dest: /etc/default/motion
      owner: root
      group: root
      mode: 0644

 - name: create motion images folder
   file:
      path: /home/pi/images
      state: directory
      mode: 0750
      owner: pi
      group: pi

 - name: set gpu memory as required for camera
   lineinfile:
      path: /boot/config.txt
      regexp: '^gpu_mem'
      state: present
      line: gpu_mem=128

 - name: ensure camera is enabled on boot
   lineinfile:
      path: /boot/config.txt
      regexp: '^start_x'
      state: present
      line: start_x=1

 - name: disable camera led to prevent window reflections
   lineinfile:
      path: /boot/config.txt
      regexp: '^disable_camera_led'
      state: present
      line: disable_camera_led=1

 - name: copy motion config file
   copy:
      src: motion.conf
      dest: /etc/motion/motion.conf
      owner: root
      group: root
      mode: 0644

 - include_tasks: service.yml
