#!/usr/bin/env python3

from threading import Thread
import subprocess
from queue import Queue
from time import time, sleep
import os


LEAVE_DELAY = 500
LOCK_FILE = os.path.expanduser("~") + "/IPHONE-AT-HOME"
HOSTS = os.environ["IPHONE_NAME"].split(',')


def remove_lockfile():
   try:
      os.remove(LOCK_FILE)
   except:
      pass


def ping(q):
   global last_seen
   while True:
      host = q.get()
      response = subprocess.call(
         "ping -c 1 -t 1 " + host,
         shell = True,
         stdout = open('/dev/null', 'w'),
         stderr = subprocess.STDOUT
      )
      if response == 0:
         last_seen = time()


def main():
   global last_seen
   q = Queue()
   home = False
   remove_lockfile()
   for host in HOSTS:
      Thread(target = ping, args=(q,)).start()
   while True:
      for host in HOSTS:
         q.put(host)
      t = time()
      if (t - last_seen) > LEAVE_DELAY:
         if home:
            print("EVENT: Device gone away " + str(t))
            remove_lockfile()
         home = False
      else:
         if not home:
            print("EVENT: Device returned home " + str(t))
            open(LOCK_FILE, 'a').close()
         home = True
      if q.qsize() > 4:
         sleep(3.0)
      sleep(1.0)

if __name__ == '__main__':
   last_seen = 0.0
   main()
